# to update 
# docker-compose stop
# docker-compose pull
# docker-compose up -d

version: "3.3"

services:
  db:
    # image: mongo:latest
    image: andresvidal/rpi3-mongodb3:latest
    networks:
      - ampnado
    ports:
      - 27017:27017
    # volumes:
    #   - /home/teresa/AmpnadoDockerData/mongodbData:/data/db

  amp:
    image: ampnado:latest
    build: .
    environment:
      - AMP_PROGRAM_PATH=/usr/share/Ampnado
      - MONGO_AMPNADO_MONGODB_ADDR=mongodb://db:27017/ampnadoDB
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - AMP_SETUP=1
      - AMP_MEDIA_PATH=/usr/share/Ampnado/Music
      - AMP_HTTP_THUMBNAIL_DIR_PATH=/usr/share/Ampnado/static/images/thumbnails
      - AMP_THUMBNAIL_DIR_PATH=/usr/share/Ampnado/static/images/thumbnails
      - AMP_NO_ART_PIC_PATH=/usr/share/Ampnado/static/images/noartpic.jpg
      - AMP_SERVER_ADDR=http://192.168.1.26
      - AMP_SERVER_PORT=6789
      - AMP_OFFSET_SIZE=45
      - AMP_USERNAME=admin
      - AMP_PASSWORD=ampnado
      # - bogus=bogus
      # - fuck=fuck
    networks:
      - ampnado
    ports:
      - 6789:6789
    volumes:
      # this points to where the music is located in the container
      - ampnadovol:/usr/share/Ampnado/Music/
      # this points to where our thumbnails are located in the container
      - ampnadopicvol:/usr/share/Ampnado/static/images/thumbnails
    depends_on:
      - db

networks:
  ampnado:

volumes:
  # mongovol:
  #   driver: local
  #   driver_opts: 
  #     type: none
  #     device: /home/teresa/AmpnadoDockerData/mongodbData
  #     o: bind

  ampnadopicvol:
    driver: local
    driver_opts: 
      type: none
      device: /home/pi/AmpnadoDockerData/picData
      o: bind

  ampnadovol:
    driver: local
    driver_opts:
      type: none
#THIS NEEDS TO BE CHANGE TO THE CORRECT PATH ON THE PI
      #device: /home/charlie/Music
      #device: /home/teresa/Videos/media
      #device: /media/pi/PiTB/
      # device: /home/teresa/Music
      device: /home/pi/Music
      o: bind
